name: Lint and format
on: [push]
permissions:
  contents: write
jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
      - run: uv run ruff check --fix-only .
      - run: uv run ruff format .
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -a -m "chore: lint and format code" || exit 0
          git push
